@startuml
class Stage {
Stage_name
life
num_of_enemy
bgm()
}

class Stage_select {
Stage_draw()
bgm()
}

class Character {
    id
    x
    y
    pose
    color
    sounds()
}

class Player {
    side
    draw()
    offensive_power
    attack_speed
    attack_method
    skill
    skill_duration
    skill_1st
    skill_ct
}

class Ghost {
}
class Dragon {
}
class Skeleton {
}

class Enemy {
    side
    draw()
    hp
    move_speed
}

class Hero {
}
class Fairy{
}
class Warrior{
}
class Boss{
}
class subBoss{
}

Character <|-- Player
Player <|-- Ghost
Player <|-- Dragon
Player <|-- Skeleton
Character <|-- Enemy
Enemy <|-- Hero
Enemy <|-- Fairy
Enemy <|-- Warrior
Enemy <|-- Boss
Enemy <|-- subBoss
@enduml